### ISSUE TITLE
Summary stats of two traits are from the same dataset

### ISSUE THREAD

**Issue by Sheeya-Dong** [chr1swallace/coloc#137]
If the summary stats of two traits are from the same dataset, can coloc be used for colocalisation tests?

**Comment by mocksu** [comment]
Do you mean from the same sample?

**Comment by Sheeya-Dong** [comment]
Yes. The gwas of two traits use the same samples. And if the two gwas have overlapping samples?------------------ Original ------------------From: mocksu  ***@***.***>Date: Fri,Nov 3,2023 5:40 AMTo: chr1swallace/coloc ***@***.***>Cc: Sheeya-Dong ***@***.***>, Author ***@***.***>Subject: Re: [chr1swallace/coloc] Summary stats of two traits are from thesame dataset (Issue #137)
Do you mean from the same sample?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chr1swallace/coloc/issues/137#issuecomment-1791575545",
"url": "https://github.com/chr1swallace/coloc/issues/137#issuecomment-1791575545",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mocksu** [comment]
> Yes. The gwas of two traits use the same samples. And if the two gwas have overlapping samples?------------------ Original ------------------From: mocksu ***@***.***>Date: Fri,Nov 3,2023 5:40 AMTo: chr1swallace/coloc ***@***.***>Cc: Sheeya-Dong ***@***.***>, Author ***@***.***>Subject: Re: [chr1swallace/coloc] Summary stats of two traits are from thesame dataset (Issue #137) Do you mean from the same sample? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#137 (comment)](https://github.com/chr1swallace/coloc/issues/137#issuecomment-1791575545)", "url": "[#137 (comment)](https://github.com/chr1swallace/coloc/issues/137#issuecomment-1791575545)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

My understanding is that colocalization does not strictly require independent samples. However, due to pleiotropy and other confounding factors, you need to pay attention to your study design and use other techniques such as bi-directional two sample Mendelian Randomization to further infer causality.

**Comment by Sheeya-Dong** [comment]
Got it! Thank you!

**Comment by chr1swallace** [comment]
mocksu is right, in all practical terms.  Theoretically, coloc requires independent samples, because we take the product of likelihoods in each sample. However, once sample size is at least modest (a few hundred), we found this had limited practical impact on coloc inference - see supplementary of Mitchelmore et al (2020) https://academic.oup.com/nar/article/48/6/2866/5766659


--
https://chr1swallace.github.io<https://chr1swallace.github.io/>

________________________________

**Comment by Sheeya-Dong** [comment]
I got it! Thanks a lot!
