### ISSUE TITLE
Error when running `check_dataset()`

### ISSUE THREAD

**Issue by martaalcalde** [chr1swallace/coloc#145]
When running `check_dataset()` with argument `req = "LD"`, it keeps appearing the error `colnames in LD do not contain all SNP`. I checked the function, and it is because the following criteria is not fulfilled: `length(setdiff(d$snp,colnames(d$LD)))`.  This is not meet as my `d$snp` is with the form `rs1` whereas when computing the LD matrix, either row names and column names are with the form `rs1_EffectAlleleValue_OtherAlleleValue`.

I think it would be nice to generalise this to be able to include LD matrix that in their row names and column names include the alleles. I suggest just changing:
```
length(setdiff(d$snp,colnames(d$LD))) ---> length(d$snp) == length(colnames(d$LD))
```
And maybe, afterwards adding:

```
if(length(setdiff(d$snp,colnames(d$LD)))){
colnames(d$LD) <- gsub("_.*","",colnames(d$LD))
row.names(d$LD) <- gsub("_.*","",row.names(d$LD))

if(length(setdiff(d$snp,colnames(d$LD))){
Error("colnames in LD do not contain all SNP")
}
}
```

I hope is useful!

**Comment by chr1swallace** [comment]
Hi Maria,

Thank you for the suggestion, but I think it is better you make the row/colnames of your LD matrix match the elements of your SNP vector. Coloc uses these to ensure the LD is correctly ordered against the beta etc

The gsub you suggest would do it, but I can't incorporate that into the function, because other people may have different forms of SNP names where they do not wish the part after the _ to be deleted.

Chris

--
https://chr1swallace.github.io
________________________________
From: Marta Alcalde-Herraiz ***@***.***>
Sent: Monday, January 22, 2024 1:16:25 PM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] Error when running `check_dataset()` (Issue #145)


When running check_dataset() with argument req = "LD", it keeps appearing the error colnames in LD do not contain all SNP. I checked the function, and it is because the following criteria is not fulfilled: length(setdiff(d$snp,colnames(d$LD))). This is not meet as my d$snp is with the form rs1 whereas when computing the LD matrix, either row names and column names are with the form rs1_EffectAlleleValue_OtherAlleleValue.

I think it would be nice to generalise this to be able to include LD matrix that in their row names and column names include the alleles. I suggest just changing:

length(setdiff(d$snp,colnames(d$LD))) ---> length(d$snp) == length(colnames(d$LD)


And maybe, afterwards adding:

if(length(setdiff(d$snp,colnames(d$LD)))){
colnames(d$LD) <- gsub("_.*","",colnames(d$LD))
row.names(d$LD) <- gsub("_.*","",row.names(d$LD))

if(length(setdiff(d$snp,colnames(d$LD))){
Error("colnames in LD do not contain all SNP")
}
}


I hope is useful!

**Comment by martaalcalde** [comment]
Hi Chris,

Thank you for your fast response. Makes sense! I'll close the issue.

All the best,

Marta

**Comment by chr1swallace** [comment]
Thanks for understanding

--
https://chr1swallace.github.io
________________________________
