### ISSUE TITLE
coloc.susie returns NA results without error message

### ISSUE THREAD

**Issue by zhilizheng** [chr1swallace/coloc#147]
Hi Dr. Wallace, 

Thanks for the great coloc tool.   I meet a problem when running the coloc.susie, that I don't understand where the problem comes from. 

Relicate of the problem: 
Data: https://www.dropbox.com/scl/fo/f0akgky4bbnglgiejykf9/h?rlkey=4zu9ki42hdu3c7323s6l2hwjd&dl=0
```r
# finemap from susie for summary data 1
f1 = readRDS("f1.rds")
# finemap from susie for summary data 2
f2 = readRDS("f2.rds")
# coloc
res=coloc.susie(f1, f2)
```
As shown in the example, the coloc results is NA, without any errors.  Could you figure me what happened here? 

BTW, the suma.rds, is the orginal summary data.  Columns with name BETA, SE, P, MAF, N were from summary data1,  BETA2, SE2, P2, MAF2, N2 were from summary data2.   

Thanks for your help.

Regards,
Zhili

**Comment by chr1swallace** [comment]
Sorry, I can't reproduce this. Could either of you send me a small example dataset that produces this error?

--
https://chr1swallace.github.io<https://chr1swallace.github.io/>

________________________________

**Comment by chr1swallace** [comment]
I just saw the data - thanks. Easy to check. The issue is that susie doesn't find any credible sets in your second dataset (shown below). That means there is nothing to colocalise. I will make a more informative warning message for this situation.

> f2$sets
$cs
NULL

$coverage
NULL

$requested_coverage
[1] 0.95

--
https://chr1swallace.github.io<https://chr1swallace.github.io/>

________________________________
