### ISSUE TITLE
runsusie() error with convergence

### ISSUE THREAD

**Issue by jvalliere** [chr1swallace/coloc#163]
Hello, I was wondering why in the runsusie() function convergence must be necessary in order to continue forward with colocalization. I had been running susie with two phenotypes in a region with ~6000 variants, and one was not reaching convergence. When I run susie_rss() myself with the data, the call does not converge but I get credible sets, which I thought could still be used for coloc. I then used annotate_susie() to make it compatible for coloc, and it worked fine. Is there a reason coloc must ensure convergence? Thank you so much for your help!

**Comment by chr1swallace** [comment]
typically if we fit an MCMC model, we require convergence so that we can be sure we are sampling from the true posterior. if a model has not converged, we might be using nonsense in the downstream coloc. if you think it's good enough, so be it, but I would want to justify that decision somehow.



--
https://chr1swallace.github.io<https://chr1swallace.github.io/>

________________________________
From: Jesse Valliere ***@***.***>
Sent: Wednesday, May 8, 2024 4:45 PM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] runsusie() error with convergence (Issue #163)


Hello, I was wondering why in the runsusie() function convergence must be necessary in order to continue forward with colocalization. I had been running susie with two phenotypes in a region with ~6000 variants, and one was not reaching convergence. When I run susie_rss() myself with the data, the call does not converge but I get credible sets, which I thought could still be used for coloc. I then used annotate_susie() to make it compatible for coloc, and it worked fine. Is there a reason coloc must ensure convergence? Thank you so much for your help!
