### ISSUE TITLE
About Differing N and s Parameters & Matching Two Datasets

### ISSUE THREAD

**Issue by maegsul** [chr1swallace/coloc#33]
Hi,

First of all, thanks a lot for developing coloc, it has been very useful so far for my projects!

I am mainly using coloc.abf (coloc v4.0.4) and my first question is regarding the sample size (N) and case/N (s) inputs. For some GWAS summary statistics files, these tend to be differing; for example, markerX is only tested in 8 out of 10 cohorts of the meta-analysis, but markerY is tested in 6 out of 10 cohorts, making the N and s different for these two markers. In this case, considering that coloc only allows single N and s input, what's the best option, is it calculating N and s based on maximal numbers? (For example, if it is a GWAS in 50K cases and 50K controls -> assign N = 100K and s = 0.5; independent of the fact that some of the markers were measured in 40K cases and 40K controls actually).

Second question: is it best practice to match two datasets prior to coloc, i.e. removing all markers that is found in dataset1 but missing in dataset2 and so forth?

Thanks in advance!
Fahri

**Comment by chr1swallace** [comment]
I have a concern with variable N and s.  coloc works by evaluating the support for association at each SNP in terms of a Bayes factor, and then comparing that Bayes factor to those at other SNPs.  If SNP A (the causal one) had only half the samples as another SNP B in strong LD with it, then its Bayes factor at A might be smaller than that at B simply because of sample size differences, leading us to erroneously conclude that SNP B was more likely to be causal.  If the other trait had more even coverage, or even coverage biased in the opposite direction, this may provide erroneous evidence against colocalisation.  I think perhaps for meta analysis, coloc rightly expects all SNPs have similar amounts of data.  Is this a situation where you have the summary data for every component, and could select a subset of studies that have consistent coverage?

This does seem inadequate though - throwing away data - I'll try and think whether there is a better way round this.

coloc should match markers if you supply snp names, but feel free to remove missing markers yourself.

**Comment by maegsul** [comment]
Thank you for your comments! What I am comparing here are an in-house eQTL catalogue (dataset1) vs a meta-analysis GWAS (dataset2). Dataset1 contains information based on a fixed number of samples always, so for this trait there shouldn't be a problem.

For dataset2 (meta-analysis GWAS), the issue arises from large consortia where many different studies are meta-analysed, and then summary statistics based on the meta-analysis is provided. For instance, this is not the one I currently work on, but as it is already publicly available I can provide it as an example:

This is summary statistics file of a recent PD GWAS (Nalls et al 2019, https://www.biorxiv.org/content/10.1101/388165v3): https://drive.google.com/file/d/1FZ9UL99LAqyWnyNBxxlx6qOUlfAnublN/view?usp=sharing . You can see differing N and s values in this file per marker. I think this mainly arises due to the fact that for large meta-analysis GWAS the imputation source is not always the same (for instance UK Biobank is imputed to a different panel if I am not wrong), neither is the data access requirements (23andme here probably only provides summary level data, etc.), so every cohort is first assayed like this, then meta-analysed - however this doesn't mean that every variant will be present (with a good imputation quality score) in each cohort.

I had a look at my own GWAS summary statistics, and it seems that the N difference between samples is quite limited (I think) -> for about ~20M variants, the minimum N for a marker was ~42K, the maximum N was ~440K; but median N is ~422K, 1st quantile is ~390K and 3rd quantile is actually as same as the maximum N. So the distribution seems fine, and bias would be limited maybe. What do you think? Also, I think when this GWAS vs my MAF > 1% eQTL catalogue is considered, the matching variants will be high likely to be goodly imputed in all cohorts thus have even a better uniform distribution for N and s I'd assume.

**Comment by chr1swallace** [comment]
I think if you use beta and varbeta, N and s are ignored

**Comment by kwcurrin** [comment]
Hello,

I am running into a similar situation where I am working with various meta-analyses that have different sample size per variant. Most of the data I am working with is quantitative traits. In most cases, I have beta and varbeta, or can estimate them. But my issue is I don't have sdY for most of the traits. So N is required to estimate sdY. I have found that coloc actually will accept a vector for the N parameter and it doesn't throw an error. Is it OK to do this (provide a vector of N values per variant)?

Thanks!

Kevin

**Comment by chr1swallace** [comment]
Hi Kevin,

I think the safe way is to estimate the trait variance in a separate
step. That function can certainly take more a vector of N.  You can do
this with the function coloc:::sdY.est() which takes the arguments:


   vbeta: vector of variance of coefficients

     maf: vector of MAF (same length as vbeta)

       n: sample size

Then, the estimated variance could be passed to coloc functions.  I
suggest this only because currently coloc functions assume (though may
not enforce) that N is a scalar, and I don't yet know whether this will
be relaxed or tightened.

Best, Chris
