### ISSUE TITLE
Separate MAFs for cases and controls

### ISSUE THREAD

**Issue by minigel** [chr1swallace/coloc#40]
Hello,

I am using summary statistics from a case-control GWAS where the MAFs of the cases and controls are provided in separate columns. Would you have recommendations on the best way to use these columns with `coloc.abf`?

Thank you!

**Comment by chr1swallace** [comment]
Ideally, you will have log odds ratios (beta) and their standard
errors, so won't need MAF.

Otherwise, I'd just pick the control.

**Comment by minigel** [comment]
Yes, I do have the betas and SEs, so I'll just use those. Thank you!

**Comment by VitorAguiar** [comment]
Hi Dr. Wallace, thanks for developing coloc.

I'm also in this situation of separate MAFs for cases and controls. However, I don't have the per-SNP SE for the betas, so I assume I need MAF.

I've read your answer for another question here that in-sample MAFs would be ideal. I was assuming that MAF in a reference population would be better, because the case-control sampling might distort MAFs by, for example, enriching for risk alleles if you have a higher proportion of cases than in the population. 

If you recommend using the in-sample MAF, should I compute a weighted average of case MAF and control MAF, given the sample sizes for cases and controls?

**Comment by VitorAguiar** [comment]
Actually, is it OK to compute varbeta with:

varbeta = log(OR)² / qchisq(p-value, df = 1, lower = FALSE)

?

**Comment by chr1swallace** [comment]
Yes, it is

https://chr1swallace.github.io
________________________________

**Comment by VitorAguiar** [comment]
Thank you @chr1swallace.

When I compute varbeta this way, I have a problem with variants with OR = 1, in which case beta and varbeta equal zero.

In your check_dataset function, which is called within coloc.abf, there is a p-value estimation at: 

```
## no beta/varbeta
  if(("s" %in% nd) && (!is.numeric(d$s) || d$s<=0 || d$s>=1))
    stop("dataset ",suffix,": ","s must be between 0 and 1")
  if(!("beta" %in% nd) || !("varbeta" %in% nd)) { # need to estimate var (Y)
    if(!("pvalues" %in% nd) || !( "MAF" %in% nd))
      stop("dataset ",suffix,": ","require p values and MAF if beta, varbeta are unavailable")
    if(d$type=="cc" && !("s" %in% nd))
      stop("dataset ",suffix,": ","require, s, proportion of samples who are cases, if beta, varbeta are unavailable")
    p=d$pvalues
  } else {
    p=pnorm( -abs( d$beta/sqrt(d$varbeta) ) ) * 2
  }

  ## minp
  if(min(p) > warn.minp)
    warning("minimum p value is: ",format.pval(min(p)),"\nIf this is what you expected, this is not a problem.\nIf this is not as small as you expected, please check the 02_data vignette.")
```

When beta and varbeta are zero, I have p = NaN. And that causes the if(min(p) > warn.minp) test to fail. As I understand, the p-value is only used for that warning.

Not sure if I should remove variants with OR=1, since you recommend not to filter based on significant or effect size. Any suggestions?

Thank you,
Vitor

**Comment by anbai106** [comment]
@VitorAguiar I encountered the same issue here to format a case-control GWAS summary, where I only know the OR and SE. Did you have a solution? 

Thanks

**Comment by chr1swallace** [comment]
just knowing the OR ( beta=exp(OR) ) and se (varbeta = se^2) should be enough information.

--
https://chr1swallace.github.io<https://chr1swallace.github.io/>

________________________________

**Comment by anbai106** [comment]
@chr1swallace Are you sure about converting OR to beta as `beta=exp(OR)` in the setting of a logistic regression? I think the way to do it is:

> beta = log(OR)
> OR = exp(beta)

Correct me if I am wrong since you are the expert here. I saw one paper explaining this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3936971/#:~:text=Logistic%20regression%20is%20used%20to,the%20observed%20event%20of%20interest.
