### ISSUE TITLE
How to interpret coloc.susie results with two different variants but has very high PP.H4.Prob?

### ISSUE THREAD

**Issue by XiaoweiHu-Stat** [chr1swallace/coloc#84]
Hi,
I used coloc.susie on gwas and eqtl with summary statistics. The results show that there are two different variants in one row with very high PP.H4.Probability (e.g., 0.99). I wonder how to interpret such result since H4: both traits are associated and share the same single causal variant.

Thank you.
Xiaowei

**Comment by chr1swallace** [comment]
Are these variants in LD?

https://chr1swallace.github.io
________________________________
From: Hu999 ***@***.***>
Sent: Friday, May 6, 2022 9:52:06 PM
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] How to interpret coloc.susie results with two different variants but has very high PP.H4.Prob? (Issue #84)


Hi,
I used coloc.susie on gwas and eqtl with summary statistics. The results show that there are two different variants in one row with very high PP.H4.Probability (e.g., 0.99). I wonder how to interpret such result since H4: both traits are associated and share the same single causal variant.

Thank you.
Xiaowei

**Comment by XiaoweiHu-Stat** [comment]
Hi Chris,

Thanks for your reply. Yes, in most cases, the two variants I found in such scenario are in high LD (e.g., genetic correlation R is 0.9).

Xiaowei
________________________________

**Comment by chr1swallace** [comment]
then the result says that the two traits share a causal variant, but we
are uncertain of what that variant is
