### ISSUE TITLE
Issue with plotting

### ISSUE THREAD

**Issue by bethleegy** [chr1swallace/coloc#89]
Hi there,

I am trying to plot the coloc.abf object as per the S3 method for class 'coloc_abf' mentioned in the vignette. However, after I have the coloc.abf run and save as an object without any issues, when I run plot(coloc_object) I get the following error: 

`Error in `:=`(c("z", "df"), tstrsplit(variable, "\\.")) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
In addition: Warning messages:
1: In melt(x, id.vars = c("snp", "position"), measure.vars = grep("z.df",  :
  The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(x). In the next version, this warning will become an error.
2: In melt(x, id.vars = c("snp", "position"), measure.vars = grep("PP",  :
  The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(x). In the next version, this warning will become an error.`

Any insight would be appreciated. Thank you!

**Comment by chr1swallace** [comment]
I'm afraid I don't see this error with my test data. Could you please share the object you are trying to plot, so I can debug? Thanks.
________________________________
From: bethleegy ***@***.***>
Sent: 31 May 2022 22:57
To: chr1swallace/coloc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chr1swallace/coloc] Issue with plotting (Issue #89)


Hi there,

I am trying to plot the coloc.abf object as per the S3 method for class 'coloc_abf' mentioned in the vignette. However, after I have the coloc.abf run and save as an object without any issues, when I run plot(coloc_object) I get the following error:

Error in :=(c("z", "df"), tstrsplit(variable, "\\.")) : Check that is.data.table(DT) == TRUE. Otherwise, := and :=(...) are defined for use in j, once only and in particular ways. See help(":="). In addition: Warning messages: 1: In melt(x, id.vars = c("snp", "position"), measure.vars = grep("z.df", : The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(x). In the next version, this warning will become an error. 2: In melt(x, id.vars = c("snp", "position"), measure.vars = grep("PP", : The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(x). In the next version, this warning will become an error.

Any insight would be appreciated. Thank you!

**Comment by bethleegy** [comment]
Thank you for the response.
[coloc_obj.RDa.zip](https://github.com/chr1swallace/coloc/files/8996053/coloc_obj.RDa.zip)

The coloc object as a zipped RDa is attached here.

**Comment by chr1swallace** [comment]
thank you so much for debugging - I will make the change in the method.
________________________________
